- hosts: localhost
  connection: local
  tasks:
    - name: bashrc
      ansible.builtin.copy:
        src: ./bashrc.sh
        dest: ~/.bashrc
    - name: vimrc
      ansible.builtin.copy:
        src: ./vimrc
        dest: ~/.vimrc
    - name: gitconfig
      ansible.builtin.copy:
        src: ./gitconfig
        dest: ~/.gitconfig
    - name: git allowed signers
      ansible.builtin.copy:
        src: ./allowed_signers
        dest: ~/.allowed_signers
    - name: gcr-ssh-agent
      ansible.builtin.systemd_service:
        name: gcr-ssh-agent.socket
        scope: user
        enabled: true
