---
- name: "Configure zmo"
  hosts: "localhost"
  tasks:
    - name: "setup bootstrap"
      ansible.builtin.import_tasks: "install.yml"
    - name: "Add myip service"
      ansible.builtin.copy:
        src: "myip.service"
        dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/myip.service"
    - name: "Add myip timer"
      ansible.builtin.copy:
        src: "myip.timer"
        dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/myip.timer"
    - name: "Add dnsupdate service"
      ansible.builtin.copy:
        src: "dnsupdate.service"
        dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/dnsupdate.service"

    - name: "Reload configs"
      ansible.builtin.systemd:
        daemon_reload: yes
        scope: "user"
    - name: "Enable bootstrap timer"
        ansible.builtin.systemd:
          state: started
          name: "bootstrap.timer"
          scope: "user"
          enabled: yes
    - name: "Enable myip timer"
      ansible.builtin.systemd:
        state: started
        name: "myip.timer"
        scope: "user"
        enabled: yes
